# Generated by Django 4.0.6 on 2024-04-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='email',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
