# Generated by Django 4.0.6 on 2024-04-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_docente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='apresentacao',
            field=models.CharField(max_length=100000),
        ),
    ]
