# Generated by Django 4.0.6 on 2024-04-20 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_curso_docentecurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='areaCientifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina', to='projeto.area_cientifica'),
        ),
    ]
