# Generated by Django 4.0.6 on 2024-04-21 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_alter_disciplina_areacientifica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='docentes',
            field=models.ManyToManyField(null=True, related_name='disciplinas', to='projeto.docente'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='linguagem',
            field=models.ManyToManyField(null=True, related_name='disciplinas', to='projeto.linguagemprogramacao'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='projeto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='projeto.projeto'),
        ),
    ]
