# Generated by Django 4.0.6 on 2024-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0006_alter_disciplina_docentes_alter_disciplina_linguagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='docentes',
            field=models.ManyToManyField(related_name='disciplinas', to='projeto.docente'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='linguagem',
            field=models.ManyToManyField(related_name='disciplinas', to='projeto.linguagemprogramacao'),
        ),
    ]
