# Generated by Django 4.0.6 on 2024-05-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0009_alter_curso_apresentacao_alter_curso_competencias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tecnologiasUsadas',
            field=models.CharField(max_length=100),
        ),
    ]
