# Generated by Django 4.0.6 on 2024-05-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0010_alter_projeto_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricaoLonga',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
    ]
