# Generated by Django 4.0.6 on 2024-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100, null=True)),
                ('ano_criacao', models.IntegerField()),
                ('fotoBanda', models.ImageField(blank=True, null=True, upload_to='bands')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('anoRealizacao', models.IntegerField()),
                ('bandas', models.ManyToManyField(related_name='festival', to='festivais.banda')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('anoRealizacao', models.IntegerField()),
                ('festivais', models.ManyToManyField(related_name='localizacao', to='festivais.festival')),
            ],
        ),
    ]
