# Generated by Django 4.0.6 on 2024-06-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Luisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apresentacao', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='bands')),
                ('competencias', models.TextField()),
            ],
        ),
    ]
