# Generated by Django 4.0.6 on 2024-06-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_banda_biografia_musica_letra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='biografia',
            field=models.TextField(blank=True),
        ),
    ]
