# Generated by Django 4.0.6 on 2024-06-10 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='defaultUser.jpg', upload_to='')),
                ('rating', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=10000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='artigos.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('cabecaNoticia', models.TextField()),
                ('noticia', models.TextField()),
                ('foto', models.ImageField(default='default.jpg', upload_to='')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='artigos.autor')),
                ('comentarios', models.ManyToManyField(related_name='artigos', to='artigos.comentario')),
            ],
        ),
    ]
